package es2

object Constants {
  val PLANET_NUMBER = 6
  val DELTA_TIME = 1
  val GRAVITY: BigDecimal = 6.67408 * 10E-11
  val PANEL_SIZE_X = 1300
  val PANEL_SIZE_Y = 700
  val PANEL_BORDER_SIZE_X = 300
  val BUTTON_SPACING = 15
  val DRAWING_PANEL_SIZE_X: Int = PANEL_SIZE_X - PANEL_BORDER_SIZE_X
  val DRAWING_PANEL_SIZE_Y: Int = PANEL_SIZE_Y
  val BUTTON_SIZE_X: Int = PANEL_BORDER_SIZE_X - BUTTON_SPACING * 2
  val BUTTON_SIZE_Y = 40
  val MIN_DISTANCE_BETWEEN_PLANETS = 10
  val MAX_MASS = 3 * 10E24
}
